const element = document.querySelector('.gallery_select');
    const choices = new Choices(element, {
      searchEnabled: false,
      itemSelectText: '',
      position: true,
      shouldSort: false,
      classNames: {
        containerOuter: 'choices1',
        containerInner: 'choices__inner1',
        input: 'choices__input1',
        inputCloned: 'choices__input--cloned1',
        list: 'choices__list1',
        listItems: 'choices__list--multiple1',
        listSingle: 'choices__list--single1',
        listDropdown: 'choices__list--dropdown1',
        item: 'choices__item1',
        itemSelectable: 'choices__item--selectable1',
        itemDisabled: 'choices__item--disabled1',
        itemChoice: 'choices__item--choice1',
        placeholder: 'choices__placeholder1',
        group: 'choices__group1',
        groupHeading: 'choices__heading1',
        button: 'choices__button1',
        activeState: 'is-active1',
        focusState: 'is-focused1',
        openState: 'is-open1',
        disabledState: 'is-disabled1',
        highlightedState: 'is-highlighted1',
        selectedState: 'is-selected1',
        flippedState: 'is-flipped1',
        loadingState: 'is-loading1',
        noResults: 'has-no-results1',
        noChoices: 'has-no-choices1'
      },
    })
